// <auto-generated />
namespace Test2_Git.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gospodarstwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gospodarstwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201903241653148_gospodarstwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
